== Cool stuff

=== Source code (inline)

[source,xml]
----
<groupId>murex.livebook</groupId>
<artifactId>livebook-config-spi</artifactId>
----

[source, java]
Service.java
----
public interface Service {
   /**
   ** Cool JavaDoc
   **/
   CoolReturnType coolMethod(CoolArgumentType argument);
}
----

[source]
----
 [source,xml]
 ----
 <groupId>murex.livebook</groupId>
 <artifactId>livebook-config-spi</artifactId>
 ----

 [source, java]
 Service.java
 ----
 public interface Service{
    /**
    ** Cool JavaDoc
    **/
    CoolReturnType coolMethod(CoolArgumentType argument);
 }
 ----
----

=== Source (included from source sets)

Given a source file, you can include parts of the file using tags

[source,java]
----
include::{sourceDir}/MyFile.java[tags=include_this]
----

[source]
----
 [source,java]
 ----
 include::{sourceDir}/MyFile.java[tags=include_this]
 ----
----

=== Keyboard shortcuts

kbd:[ESC] or kbd:[<-] to go back

kbd:[CTRL+ALT+DEL] to turn on the alarm

[source]
----
:experimental: true

kbd:[ESC] or kbd:[<-] to go back

kbd:[CTRL+ALT+DEL] to turn on the alarm
----

=== Formulas

latexmath:[E = \alpha + \beta Y^{\gamma} + \epsilon + Awesome]

[source]
----
:stem: latexmath

latexmath:[E = \alpha + \beta Y^{\gamma} + \epsilon + Awesome]
----

=== GraphViz

http://www.graphviz.org/

[graphviz, gen-name, svg]
....
digraph g {
    {
      node [margin=0 shape=circle style=filled]
      A [fillcolor=white]
      B [fillcolor=white]
      C [fillcolor=white]
    }
    A -> C
    B-> C
}
....

[source]
----
[graphviz, gen-name, svg] <1>
....
digraph g { <2>
    {
      node [margin=0 shape=circle style=filled]
      A [fillcolor=white]
      B [fillcolor=white]
      C [fillcolor=white]
    }
    A -> C
    B-> C
}
....
----
<1> Macro, starting with diagram type, then diagram name, then output format
<2> Graphviz content

=== Plant UML

http://www.plantuml.com/

[plantuml,gen-seq-diagram]
....
@startuml
autonumber
title My Sequence diagram
participant A
participant B
participant C
->A:hi()
A->B:howAreYou()
B->C:cio()
@enduml
....

[source]
----
[plantuml,gen-seq-diagram] <1>
.... <2>
@startuml
autonumber
title My Sequence diagram
participant A
participant B
participant C
->A:hi()
A->B:howAreYou()
B->C:cio()
@enduml
....
----
<1> Macro, stating with diagram type, then diagram name
<2> plantuml content

=== Ditaa

http://ditaa.sourceforge.net/

[ditaa,gen-component-diagram]
....
                            +-----------------+
                            | {d}             |
                            |   The big guy   |
                            |                 |
                            +-----------------+
                                     |
                                     |
                                     |
              +----------------------+
              |                      |
        /-----------\          /-----------\
        | c14B      |          | cB14      |
        |   Small   |          |   Small   |
        |    Guy    |          |    Girl   |
        \-----------/          \-----------/
              |                      |
              | Towards split        | Towards rounded
              v                      v
         +---------+           /-----------\
         | Split 1 |           | cB14      |
         +---------+           | Rounded   |
         | Split 2 |           |           |
         +---------+           \-----------/
....

[source]
----

[ditaa,gen-component-diagram] <1>
.... <2>
      +-----------------+
      | {d}             |
      |   The big guy   |
      |                 |
      +-----------------+
             |
             |
             |
      +----------------------+
      |                      |
/-----------\          /-----------\
| c14B      |          | cB14      |
|   Small   |          |   Small   |
|    Guy    |          |    Girl   |
\-----------/          \-----------/
     |                      |
     | Towards split        | Towards rounded
     v                      v
+---------+           /-----------\
| Split 1 |           | cB14      |
+---------+           | Rounded   |
| Split 2 |           |           |
+---------+           \-----------/
....
----
<1> Macro, stating with diagram type, then diagram name
<2> ditaa content
